### ISSUE TITLE
Error when index an updated solr schema

### ISSUE THREAD

**Issue by fpousserot** [lucidworks/spark-solr#102]
When a solr schema is updated, spark-solr detect new fields and it fail with this message : 

spark.solrRelation : Sending request to Solr schema API to add 1 fields.
impl.CloudSolrClient : Request to collection xxxxx failed due to (405) .... Exepected mime type application/octet-stream but got text/html

**Comment by thelabdude** [comment]
thanks for the report, I'll dig into that and see what's up

**Comment by risdenk** [comment]
So I'm not entirely sure this is related but just an idea:

https://github.com/apache/lucene-solr/blob/master/solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClient.java#L531

I was looking around there for HttpSolrClient failing when 401 was hit. If any of the HttpStatus doesn't match then it tries to check mime type. So basically Solr is then trying to wrap the 405 (or 401 error) with something else and it fails.

**Comment by risdenk** [comment]
This was the original message I sent to the Solr dev list:

http://mail-archives.apache.org/mod_mbox/lucene-dev/201603.mbox/%3CCAAtMDmPVmWX4EHjN0B%3DS30wyCk0MX7zX5k492cU7GNNbTi1PBA%40mail.gmail.com%3E

**Comment by risdenk** [comment]
@fpousserot - What version of Solr are you using? Do you have a schema.xml or managed schema?

My quick guess is that it is not a managed schema and therefore the modification attempt fails with the 405.

**Comment by kiranchitturi** [comment]
as @risdenk pointed out, this should be something to do with the schema type. if you are not using managed schema, the only way to get rid of this error is to pre-define all the field names before indexing
