### ISSUE TITLE
Latest Version?

### ISSUE THREAD

**Issue by dale-chang91** [lucidworks/spark-solr#112]
Happy new year all,

I am hoping to use this for Java 8, Scala 2.11, Spark 2.0, and Solr 6.3.0
Which version of lucidworks spark-solr should I use?

**Comment by kiranchitturi** [comment]
I recommend using [3.0.0-alpha2]( http://search.maven.org/#artifactdetails%7Ccom.lucidworks.spark%7Cspark-solr%7C3.0.0-alpha.2%7Cjar).

It is compiled with Solr 6.2.1 but should work with 6.3.0 too. Let me know if it doesn't work.

Also, in a few days I will be releasing a new version of spark-solr with bug fixes and Solr 6.3.0

**Comment by kiranchitturi** [comment]
https://github.com/lucidworks/spark-solr#version-compatibility
