### ISSUE TITLE
What version to use with Solr 5.1.0, Spark 1.5.1, and Java 1.8

### ISSUE THREAD

**Issue by theyaa** [lucidworks/spark-solr#121]
What version of Spark-Solr should I use when I have Solr 5.1.0, Spark 1.5.1, and Java 1.8?

Currently your package is throwing exceptions sending data from spark streaming to solr.

**Comment by kiranchitturi** [comment]
Please check https://github.com/lucidworks/spark-solr#version-compatibility for compatible release
