### ISSUE TITLE
Query on Indexed data? Version 2.0.4

### ISSUE THREAD

**Issue by mkanchwala** [lucidworks/spark-solr#124]
Hi,

I have Solr5 instance installed, And I tried the following :

CREATE TEMPORARY TABLE temp USING solr OPTIONS (collection "temp", dv "true", zkhost "hdp-example:2181/ranger_audits" )

<field name="stored_1" type="string" indexed="true" stored="true" docValues="false" />
<field name="stored_2" type="string" indexed="true" stored="true" docValues="false" />
<field name="indexed_1" type="string" indexed="true" stored="true" docValues="false" />

Then I ran query on my indexed fields like

Select stored_1, stored_2 from temp where indexed_1 = "Something" Limit 100;

But it throws : 

Exception in thread "main" java.sql.SQLException: org.apache.spark.sql.AnalysisException: cannot resolve 'indexed_1' given input columns: [stored_1, stored_2]; line 1 pos 27
	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:282)
	at org.apache.hive.jdbc.HiveStatement.executeQuery(HiveStatement.java:378)

I don't want the Index values to be DV enabled. Is there any way I can ran queries on pure indexed values?

**Comment by thelabdude** [comment]
is indexed_1 stored? If not, then the schema creation code for the DataFrame won't see it ... you'll have to push the query criteria into the options when defining your table
