### ISSUE TITLE
On Multivalued String fields only get the first value

### ISSUE THREAD

**Issue by jugaji** [lucidworks/spark-solr#133]
When we have Multivalued fields like this in schema:
\<field name="arrayString-1" type="string" indexed="true" stored="true" required="false" multiValued="true"\/>

Spark only get the first value when we connect to de collection. ON spark-solr 1.2.0 that not happen, but in spark-solr 2.0.4 exist this bug.

Example:
sqlContext.read.format("solr").options(Map("zkHost" -> "host1:2181,host2:2181,host3:2181", "collection" -> "collection")).load()

On spark-solr 1.2.0 the result for that field is:
+----------------------------+------------------------------------------------+
|name                           |arrayString-1                                                   |
+----------------------------+------------------------------------------------+
|name1                        |[560d53db6584a8ebfab1b85c, 569653c46584a85830374460]                          |

on spark-solr 2.0.4 the result for that field is wrong only the first: 
+-------------------+-------------------------------------------------+
|name                |arrayString-1                                             |
+-------------------+-------------------------------------------------+
|name1             |560d53db6584a8ebfab1b85c                    |

**Comment by kiranchitturi** [comment]
By default, we flatten the multiValued fields and only use the first value. If you want all the values for the field be returned, please enable this in the options https://github.com/LucidWorks/spark-solr#flatten_multivalued
