### ISSUE TITLE
Kerberosed Solr Cloud

### ISSUE THREAD

**Issue by jesse758** [lucidworks/spark-solr#134]
Kerberos authentication doesnt work.
I am trying to index into a Kerberosed Solr cloud cluster via DataFrame.
Unit test works from local to server, but when I run .jar via spark-submit, indexing fails with 401 error.
I believe the root cause is for local unit test, both driver and executor are running within the same JVM, so the VM args (include java.security.auth.login.config = jaas-client.conf, etc) could be picked up by executors. But in cluster mode, executors and driver may be in different JVMs.
I have tried using spark.executor.extraJavaOptions in spark-submit with the same VM args I used for unit test, but still fails.
I am using Spark 1.6.2, Solr 5.5 and Spark-Solr-2.0.4.jar
Any suggestion would be apprecaited.
Thanks.

**Comment by kiranchitturi** [comment]
Looking into this

**Comment by kiranchitturi** [comment]
It should work by setting `spark.executor.extraJavaOptions`. I have just tested it on my side with the latest version of spark-solr

There might be a problem in the version you are using. There was a fix for kerberos that made it to spark-solr 2.1.0. 

Could you try with 2.1.0 ?

**Comment by kiranchitturi** [comment]
Also, the latest version of spark-solr is well tested against Kerberos Solr. Please try and open new tickets for issues you might encounter

https://github.com/LucidWorks/spark-solr#version-compatibility
