### ISSUE TITLE
Bulk indexing without checking for duplicates

### ISSUE THREAD

**Issue by dmcarba** [lucidworks/spark-solr#140]
Hello,

I need to speed up indexing by removing the dup check (indexing performance is degrading over time on big collections). How can I specify "update=false"  when saving to the collection?
Is it enough to set as unique key in the schema an UUID?

Thanks!

**Comment by kiranchitturi** [comment]
Hi,

I am not sure what you are asking for here. Do you want to specify query params for requests during indexing? (This option is not available yet)

Where is `dup check` happening ? Is it in Solr?

**Comment by dmcarba** [comment]
Hi,

Yes, is a specific parameter for allowing duplicates during indexing. So I understand additional params are still not supported during indexing.

Thanks

**Comment by kiranchitturi** [comment]
If you don't mind getting your hands dirty, start from here https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/com/lucidworks/spark/SolrRelation.scala#L665. It shouldn't be too hard to support additional params during indexing
