### ISSUE TITLE
Spark-solr building jar using maven issue

### ISSUE THREAD

**Issue by omeralvi** [lucidworks/spark-solr#143]
Hi 
To begin with, I am new to github so excuse me if I am posting at the wrong place. 

I am struggling with building jar files using maven for spark-solr.  I have scala 2.10.5 installed with spark 1.6.2, solr version is 5.2.1 and pom.xml is attached  
[pom.xml.txt](https://github.com/lucidworks/spark-solr/files/969637/pom.xml.txt)

When I run  

> mvn clean package -DskipTests -e

below is the error I am getting.

> [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project spark-solr: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed. CompileFailed -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project spark-solr: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
>         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
>         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
>         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
>         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
>         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
>         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
>         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
>         at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ........
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed.
>         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
>         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
>         ... 19 more
> 
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
>

**Comment by kiranchitturi** [comment]
@omeralvi What branch are you using? `master` branch only compiles with Scala 2.11

For the versions you mentioned, try with `2.0.4` branch https://github.com/lucidworks/spark-solr/tree/2.0.4

**Comment by kiranchitturi** [comment]
versions number here https://github.com/lucidworks/spark-solr#version-compatibility usually match to the branch names

**Comment by omeralvi** [comment]
Many thanks Kiran,
It worked :+1:
