### ISSUE TITLE
solr-core dependency

### ISSUE THREAD

**Issue by koertkuipers** [LucidWorks/spark-solr#15]
hello!
i was wondering, why is solr-core a dependency? it brings in a ton of what i believe to be unneeded transitive dependencies.
shouldn solrj be enough to talk to solr?

**Comment by thelabdude** [comment]
it's needed for the embedded Solr server used for document matching. dependencies are shaded so they shouldn't have any negative side-effect.

**Comment by koertkuipers** [comment]
What does this document matching do? I was able to remove all these
dependencies massively simplifying the package (and no more need for
shading either)by deleting this document matching and a few examples that
use it. This did not seem to affect my ability to write/read RDDs or
DataFrames in any way.

**Comment by thelabdude** [comment]
document matching matches documents against a known set of queries (google it). It's a valid use case and I'm keeping the dependency, so probably best if you fork off to maintain the changes to remove those features.

**Comment by koertkuipers** [comment]
thanks
ok i will keep inhouse fork
