### ISSUE TITLE
Data not getting reflected in streaming App

### ISSUE THREAD

**Issue by adymimos** [lucidworks/spark-solr#151]
I was creating an app which grabs data from Apache Kafka and do sentiment and put the data into a solr collection. To write to the solr collection I'm using `indexDStreamOfDocs` function. Data is added but its not reflected to queries. If I do collection reload, data is getting reflected. How to make data reflected to query as soon as the data is added.
    
    SolrSupport.indexDStreamOfDocs(zkHost,
        collectionName,
        10,
        tweetSentiments)

**Comment by thelabdude** [comment]
enable soft commits on your collection
