### ISSUE TITLE
why does solr update data slowly?

### ISSUE THREAD

**Issue by jhkkhtd** [lucidworks/spark-solr#155]
Hello , These days i am confused, i tried to write data from spark to solr , After spark jobs are done successfully, i opened solr to lookup datas ,there are nothing ,and the logs are not errors ,what happend ?

And the shards show something below :     
                                 
                                      Version         Gen     Size
Master (Searching) 1497342016208    362  1.11 GB
Master (Replicable) 1497343812972   434

help me please.

**Comment by kiranchitturi** [comment]
Did you check by doing a hard commit?

**Comment by jhkkhtd** [comment]
Sorry , i can't understand what you mean .  I wonder why i can't find data in solr  after spark cluster has done successfully ? whether  are they cached in the  memory of solr cluster?

**Comment by kiranchitturi** [comment]
Please read https://cwiki.apache.org/confluence/display/solr/UpdateHandlers+in+SolrConfig#UpdateHandlersinSolrConfig-Commits

**Comment by kiranchitturi** [comment]
You could also try soft commit option https://github.com/LucidWorks/spark-solr#soft_commit_secs which should make the docs visible automatically
