### ISSUE TITLE
use spark beeline to read solr

### ISSUE THREAD

**Issue by jhkkhtd** [lucidworks/spark-solr#159]
HI ,Now i want to use spark bin/beeline client to read data from solr .   can i use these project ?

**Comment by kiranchitturi** [comment]
Inject the spark-solr shaded jar to the thrift server and then you should be able to use beeline to read data from solr

**Comment by jhkkhtd** [comment]
@kiranchitturi  I have  done  like you suggested , but i don't know how to create a table , i did like these :  create external table  first (address_ntcn string,company_ntcn string,constellation_ntcn string,flag_ntcn string,inputtime_ntcn string,school_ntcn string,uid_ntcn string,userid_ntcn string,username_ntcn string,id string)  location '/tmp/solr'
 tblproperties('solr.zkhost'  '192.168.3.50:2181,192.168.3.51:2181,192.168.3.52:2181','solr.query' = '*:*','solr.collection'= 'friendslist','solr.primary_key'='id');
Am i right ,? give me another suggestions ,please . Thanks alot !

**Comment by kiranchitturi** [comment]
Example for loading a collection in Solr as a table

```
CREATE TABLE default USING solr OPTIONS (zkhost "localhost:9983/lwfusion/3.0.0-beta5/solr", collection "friendslist");
```

**Comment by kiranchitturi** [comment]
Closing as this thread is inactive
