### ISSUE TITLE
Filter fields that contain colons ":"

### ISSUE THREAD

**Issue by ariotis** [lucidworks/spark-solr#160]
In all of my collections I have several fields that contain colons in their values, IE: "something:somethingElse".

When constructing a Solr query through a direct web call, I can escape and query Solr fine:

`fq=myField:something\:somethingElse`

or I can quote the string:

`fq=myField:"something:somethingElse"`

When I create a DataFrame from this collection, if I attempt to filter by this value I get a hard error because the solr query parser isn't escaping or quoting my values:

`df.filter(df['myField'] == "something:somethingElse")`

yields: ERROR impl.CloudSolrClient: Request to collection.... Encountered " ":" ": "" at line 1, column 11.

I can see on the Solr log side the query comes across like this:

`....q=*:*....fq=myField:something:somethingElse`

This makes sense, so I've tried escaping and quoting the value:

`df.filter(df['myField'] == "something\:somethingElse")`

or

`df.filter(df['myField'] == '"something:somethingElse"')`

These end up creating valid queries to Solr and I can see in the Solr logs that Solr got a hit:

`....q=*:*....fq=myField:something\:somethingElse...} hits=1`

However the returning DataFrame is empty.

I'm guessing the data is being double filtered?  Once in Solr and then again in Spark.  The Solr query is respecting the escaped character, but the Spark filter is treating it as a literal.  IE solr sees "something:somethingElse" and Spark sees "something\:somethingElse".

Is there a way around this?  Leveraging solr.params and hardcoding a fq won't work for my use case, I need to rely on the Spark API for my filtering.

**Comment by kiranchitturi** [comment]
Hi,

What you said is right. Solr needs special characters to be escaped in filter queries and if they are escaped in the Dataframe, then Spark sees a different value to filter and it will just drop everything.

I think this should help your usecase https://github.com/lucidworks/spark-solr/pull/162/files

Can you try that out?

**Comment by ariotis** [comment]
That worked perfectly, thank you!
