### ISSUE TITLE
Compatibility with Spark 1.6.0

### ISSUE THREAD

**Issue by Prophet32j** [lucidworks/spark-solr#167]
Is it possible to use spark-solr with Spark 1.6.0? I understand it's not listed in the Compatibility Chart. Will the library error out if it detects a wrong version?

**Comment by kiranchitturi** [comment]
It should be fine to use 2.0.4. Although I have not tested, you should be able to use any spark-solr version that is compatible with 1.6.x

**Comment by Prophet32j** [comment]
Yes. So far I haven't seen an issue. It at least compiles and is able to create a new SolrRDD.
