### ISSUE TITLE
possible to create a datasource on Solr dataset?

### ISSUE THREAD

**Issue by bluejoe2008** [LucidWorks/spark-solr#17]
hi, i see a SparkRDD is provided.
if the SparkSQL datasource interface is provided?
thus we can use SQL to query on Solr.

**Comment by thelabdude** [comment]
yes, see the blog I wrote about it:

https://lucidworks.com/blog/solr-spark-sql-datasource/

**Comment by bluejoe2008** [comment]
in the web page you provided
i see the instructions for DataFrame-style usage
but i have not found a external data source definition like:

```
CREATE TABLE tweets
USING org.apache.spark.sql.solr
OPTIONS (
  ...
);
```

can you give me an example?

**Comment by thelabdude** [comment]
I've never seen that syntax in Spark-land ... can you direct me to the Spark documentation that describes that feature? The instructions I provided allow you to register a Solr collection as a temp table, so I'm not sure what the above provides you anyway?

**Comment by bluejoe2008** [comment]
spark-sql allows use CREATE TABLE command to create new external tables, which metadata will be stored in HIVE.
a good news is that, i found the correct way to create a 'solr' table based on your code:

```
CREATE TABLE solr
USING solr.DefaultSource
OPTIONS (
zkHost 'dmp0:2181,dmp1:2181,dmp2:2181', 
collection 'collection1'
);

select * from solr where col1_s='满族' and col2_s='硕士' limit 5;
...
```

the above commands work well in ./bin/spark-sql :)
great work! thank you!
