### ISSUE TITLE
use

### ISSUE THREAD

**Issue by snail4321** [lucidworks/spark-solr#171]
Greetings
I have a simple question about the Troubleshooting Tips mentioned -- Why is # _dataFrame.count_ so slow?
Execute SQL Query, select count (*), What should I do to use SolrQuerySupport.GetNumDocsFromSolr utility function.
I saw in SolrRDD.scala solrCount function definition, def solrCount: BigInt = SolrQuerySupport getNumDocsFromSolr (collection, zkHost solrQuery), but I still don't know how to use.It's so sad that
I am a novice,just like a landlubber in deep water can't swim. 
Who can help me for sure, thank you very much!

**Comment by snail4321** [comment]
In the spark-solr program, insert the code in the last page of your Shared twitter slide - Plugging in Custom strategies, and CompileFailed:
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project spark-solr: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed. CompileFailed -> [Help 1]
[ERROR]
![image](https://user-images.githubusercontent.com/30261192/30633662-18461e1e-9e1f-11e7-9bf3-ebf05d96d7c0.png)

**Comment by snail4321** [comment]
In the spark-solr program, insert the code in the last page of your Shared twitter slide - Plugging in Custom strategies, and CompileFailed:
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project spark-solr: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile failed. CompileFailed -> [Help 1]
[ERROR]
![image](https://user-images.githubusercontent.com/30261192/30633662-18461e1e-9e1f-11e7-9bf3-ebf05d96d7c0.png)

**Comment by kiranchitturi** [comment]
You can't use the code in the slide directly. I have just used some pseudo code there. Unfortunately, we don't have the time cycle or plans to port this feature to spark-solr right now.

**Comment by baisezhuzhu** [comment]
Hello, may I ask if the strategy in the slide is added to spark or in spark-solr?
Thanks for your help.
