### ISSUE TITLE
Term Vectors from SolrRDD

### ISSUE THREAD

**Issue by dale-chang91** [lucidworks/spark-solr#175]
Currently SolrRDD does not seem to support the /tvrh term vector request handler. Several individuals, as well as myself, would like to see this reintroduced to take advantage of Solr's build-in TF-IDF calculation

**Comment by kiranchitturi** [comment]
Hi Chang,

you are correct that SolrRDD does not support `/tvrh` term vector handler. We don't have plans for it in the Road map (unless it becomes a priority)

Having said that, we welcome patches for the project. I think it shouldn't be hard to add a class that extends SolrRDD and supports `/tvrh` handler. Take a look at 

1. https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
2. https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/com/lucidworks/spark/rdd/SelectSolrRDD.scala#L46
3. https://github.com/lucidworks/spark-solr/blob/master/src/main/java/com/lucidworks/spark/query/StreamingResultsIterator.java

**Comment by kiranchitturi** [comment]
Closing an issue as the thread is inactive. Please open a new issue if you have trouble implementing the terms vector handler
