### ISSUE TITLE
Documentation/Examples for StreamingSolrRDD

### ISSUE THREAD

**Issue by C0mmander198** [lucidworks/spark-solr#181]
Can someone point me to an example using this streaming feature. I read the readme, but I don't get it working. I looked through some examples in this project, but can't find anything simple and straight forward. I guess it's my fault, but would be really helpful if someone could get me started.
I'm running an example with SelectSolrRDD, which is working fine.

I tried to create something along the same lines, but have no idea which function and or parameter to use....

This is not working:
```
val streamingRDD = StreamingSolrRDD("myserver:2181","mycollection",sc)
val rdd = streamingRDD.query("q=something") 
```
2181 is the port of my zookeeper. Same settings are working with SelectSolrRDD - so generally the setup is working. It's just that I don't know how to get the stream working...

**Comment by kiranchitturi** [comment]
The StreamingSolrRDD uses `/export` handler under the hood. Your query should fit the criteria for using the export request handler. See https://lucene.apache.org/solr/guide/6_6/exporting-result-sets.html

On the other hand, if you use Dataframes to get data, then the code will resolve the handler to use based on the query
