### ISSUE TITLE
Select solr fields that contains colon :

### ISSUE THREAD

**Issue by dmalaescu** [lucidworks/spark-solr#183]
I have multiple fields in a collection that it's schema contains colon ":" in the field names. Trying to get this using the spark dataframe API results in a error : 
Code:
```
val df = sparkSession.read.format("solr").options(options).load.select("og:title_t_md")
    df.printSchema()
    df.where($"og:title_t_md" =!= "null").show(10, 100)
```

Error:
```
HttpSolrClient$RemoteSolrException: Error from server at http://172.17.0.2:8983/solr/collection_rcp_shard1_replica1: undefined field og, retry? 0
```
Trying to escape the field name in the dataframe results into an error saying that the columns cannot be found:
```
org.apache.spark.sql.AnalysisException: cannot resolve '`og\:title_t_md`' given input columns: [og:title_t_md];;
```
Is there a way select fields from solr that contains ":" in their name ?
Thanks

**Comment by kiranchitturi** [comment]
Try using alias option when defining the dataframe (https://github.com/lucidworks/spark-solr#fields) . Maybe that will work for these special characters in fields

**Comment by dmalaescu** [comment]
I have try to give an alias to the field, but the dataframe is unable to see it. If I print the dataframe schema it isn't there.

**Comment by kiranchitturi** [comment]
Solr doesn't support characters other than alpha numeric or underscore. Please see https://lucene.apache.org/solr/guide/7_4/defining-fields.html

We are open for contributions!
