### ISSUE TITLE
Solr support for Structured Streaming

### ISSUE THREAD

**Issue by matteobovetti** [lucidworks/spark-solr#185]
I need to use support for the Dataframe for Solr with Structured Streaming.
When I write I have this error.

Caused by: java.lang.UnsupportedOperationException: Data source solr does not support streamed writing

This operation is unsupported in 3.2 for spark 2.2?

Eventually the support is in roadmap?

**Comment by kiranchitturi** [comment]
I think we will support this but no promises on release version

**Comment by AEKurt** [comment]
Any updates about this feature ? Same problem on spark-solr 3.6.1 and spark 2.4.0

**Comment by kiranchitturi** [comment]
I have added this to 3.7.1 version of spark-solr
