### ISSUE TITLE
Partial updates

### ISSUE THREAD

**Issue by fjavieralba** [lucidworks/spark-solr#189]
Hi, I would want to know how to achieve the following using spark-solr:

I have disjoint information for the same document in different Spark Dataframes. E.g:

```scala
scala> users.show
+---+-----------+------------+-------+
| id|description|         job|country|
+---+-----------+------------+-------+
|123|I play golf|golf teacher|  spain|
+---+-----------+------------+-------+


scala> users2.show
+---+-------------+
| id|friends_count|
+---+-------------+
|123|          500|
+---+-------------+
```

I index one of them in SolR:

`users.write.format("solr").options(options).save`

And I have the correct document indexed:

```json
{
    "doc": {
        "id": "123",
        "description": "I play golf",
        "job": "golf teacher",
        "country": "spain",
        "_version_": 1585235445108703232
    }
}
```

But then, I want to **add** the information from the second Dataframe, **without deleting the existing fields**. I.e, I want to do a partial update from Spark, using spark-solr.

If I index my additional information in `users2`, my original data is removed from Solr:

`users2.write.format("solr").options(options).save`

```json
{
    "doc": {
        "id": "123",
        "friends_count": 500,
        "_version_": 1585235548973301760
    }
}
```

How could I configure spark-solr so all writes are considered updates?
The result I want to obtain from my second write is:

```json
{
    "doc": {
        "id": "123",
        "description": "I play golf",
        "job": "golf teacher",
        "country": "spain",
        "friends_count": 500,
        "_version_": 1585235445108703232
    }
}
```

Joining the two dataframes in Spark is not a solution, since they will be available at different times, and I need to update the info as soon as I get it in Spark.

Is this possible using spark-solr?

**Comment by kiranchitturi** [comment]
Check my response to https://github.com/lucidworks/spark-solr/issues/197
