### ISSUE TITLE
Support for PySpark

### ISSUE THREAD

**Issue by smouzakitis** [lucidworks/spark-solr#192]
Hello,

I would like to ask if the project can be used with pySpark. For instance if i can run this code you have in the example in python and not scala.

val options = Map(
  "collection" -> "{solr_collection_name}",
  "zkhost" -> "{zk_connect_string}"
)
val df = spark.read.format("solr")
  .options(options)
  .load

**Comment by kiranchitturi** [comment]
yes, you should be able to do the same in pyspark. 

```
df = spark.read.format("solr").option("collection", "logs").load()
```

Maybe try construct a dictionary with opts and pass it via options

**Comment by kiranchitturi** [comment]
You are welcome to contribute any python examples that you got working

**Comment by appunnicer13** [comment]
What about support for indexing in pyspark ?

**Comment by kiranchitturi** [comment]
Indexing should work the same if you are writing from a dataframe

**Comment by sarvanrallev** [comment]
I tried like below but i could't able to achieve the result
solr_df = sparkSession\
            .read\
            .format("solr")\
            .option("collection","exammple")\
            .option("zkhost","192.168.1.191:2181")\
            .load()

i am getting below error
" java.lang.NoSuchMethodError: org.apache.solr.client.solrj.impl.HttpClientUtil.createClient(Lorg/apache/solr/common/params/SolrParams;)Lorg/apache/http/impl/client/CloseableHttpClient"

i am using httpclient 4.4.1 and httpcore 4.4.1.
