### ISSUE TITLE
Atomic Updates

### ISSUE THREAD

**Issue by Ostap26** [lucidworks/spark-solr#197]
how it is possible to make Atomic Updates with Solr Spark ? 

I need to update an existing document with new fields , without overriding or deleting existing ones

**Comment by parisni** [comment]
Hi
I  need this feature. I have explored the code and your advice and I d like your feedback before implentation.

- create a SolrInputDocument from a RDD to update
  - consider every fields from DF to be SET (cf: https://lucene.apache.org/solr/guide/7_5/updating-parts-of-documents.html#atomic-updates)                                                                       
  - consider the ID field as the key, if not exists use the first column
  - provide an enum for SaveMode (default=Overwrite, AtomicUpdate) and activate the mode in https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/solr/DefaultSource.scala
  - add the update method and use it for AtomicUpdate to spark-solr-master/src/main/scala/com/lucidwork s/spark/SolrRelation.scala                                                                                                                                                               
  - see solrJ way for atomic update http://yonik.com/solr/atomic-updates/                                                                                                                                       
  - use the indexDocs to index the documents: https://github.com/LucidWorks/spark-solr/blob/edba79f97c9baa334f11a91ec39ab9c4a4fd7d74/src/main/scala/com/lucidworks/spark/util/SolrSupport.scala#L303-L302        
                                                                                                                                       
                                                                                                                                                                                                                 
It will enable such API: 

``` scala                                                                                                                                                                                        
df.write                                                                                                                                                                                                         
  .format("solr")                                                                                                                                                                                                
  .mode(SolrSaveMode.AtomicUpdate)                                                                                                                                                                               
  .options(option)                                                                                                                                                                                               
  .save
```

**Comment by sanjanarjn** [comment]
@parisni @kiranchitturi  Is the atomic update change available in the latest Spark-Solr versions?

**Comment by sanjanarjn** [comment]
I am trying the update from PySpark, not sure how to achieve this. Any help would be appreciated!

**Comment by losforword** [comment]
@kiranchitturi Can you please confirm if Solr partial update is in place or if there are any branches ?

**Comment by falloutdurham** [comment]
You'll still have to use the method that Kiran mentioned up above.
