### ISSUE TITLE
unresolved dependency: org.restlet.jee

### ISSUE THREAD

**Issue by jcoutino** [lucidworks/spark-solr#198]
I am currently using Spark 2.2.0, SBT and connector version 3.3.4
I have the the following Scala SBT dependency "com.lucidworks.spark" % "spark-solr" % "3.3.4", however, getting the following unresolved dependency: org.restlet.jee#org.restlet;2.3.0 not found
Thanks

**Comment by jcoutino** [comment]
Resolved with jeisinge fix Shade HTTP Client and Scala Logging (#195)
spark-solr-3.5.0-20180207.063358-3-shaded

**Comment by sudheerr48** [comment]
@jcoutino  I am new to Shading in sbt , would you post the http client and scala logging shading code (in sbt) here please
