### ISSUE TITLE
cannot resolve spark-solr dependency:  org.restlet.jee

### ISSUE THREAD

**Issue by fjavieralba** [lucidworks/spark-solr#200]
Hi,

I'm trying to use Spark 2.2.0 with spark-solr 3.3.4, but I'm consistently having an issue with a spark-solr dependency that cannot be retrieved: 

```
                ::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: org.restlet.jee#org.restlet;2.3.0: not found

		:: org.restlet.jee#org.restlet.ext.servlet;2.3.0: not found

		::::::::::::::::::::::::::::::::::::::::::::::
```

I've tried erasing maven, ivy and gradle caches, but no luck.

Any hint?

**Comment by kiranchitturi** [comment]
See https://github.com/lucidworks/spark-solr/issues/198

**Comment by fjavieralba** [comment]
Thanks @kiranchitturi
