### ISSUE TITLE
withSolrUrl support

### ISSUE THREAD

**Issue by kikurin-ibm** [lucidworks/spark-solr#201]
Do we have any way to use `spark-solr` with an HTTP URL? Sometimes I  can't know the ZK HOST.

I know there is a cache inside for `HttpSolrClient` and its key is based on zk host and shard url.  So I guess there is no way so far but let me confirm.

I mean I want to build a `HttpSolrClient` like following:

`new CloudSolrClient.Builder().withSolrUrl("http://localhost:8983/solr").build();`

**Comment by kiranchitturi** [comment]
We only support SolrCloud which always has a `zkhost` connect string. Http support is not present
