### ISSUE TITLE
Java 1.7 - Spark 2.1.0

### ISSUE THREAD

**Issue by sunny1978** [lucidworks/spark-solr#205]
Spark 2.1.0 based spark-solr latest version is 3.0.0-beta3 as per Readme. 
All these are java 1.8 based. For some reasons, we could not move to jdk 1.8 yet.
Do you have any spark 2.1.0 based and with jdk 1.7? 
If Not, kindly advice us on how to force re-build so that I get 1.7 based spark-solr uber jar.

**Comment by sunny1978** [comment]
@kiranchitturi Hi - is it possible to get a spark-solr with java 1.7?
Spark: 2.1.0
Scala: 2.11
Java: 1.7
Right now I see 3.0.0-beta4 is the latest for spark 2.1.0. Can you help me recompile this using 1.7 and build a uber jar? I tried download and change the java.version to 1.7. But this lands me to runtime error

java.lang.UnsupportedClassVersionError: org/apache/solr/common/SolrInputDocument : Unsupported major.minor version 52.0

spark-solr-3.0.0-beta4.jar --> 683KB
spark-solr-3.0.0-beta4-shaded.jar --> 55241 KB

If possible share a pom file that helps me rebuild for 1.7 java

**Comment by kiranchitturi** [comment]
> What we want:
Spark: 2.1.0
Solrj: 5.5.x
Scala: 2.11
Jdk 1.7

We don't have any release that works with the above combination. Your best bet is to fork the spark-solr repo, modify https://github.com/lucidworks/spark-solr/blob/master/pom.xml#L39 and work towards the specific versions you need. It might lead to compile issues but they can be easily worked around
