### ISSUE TITLE
Can not use spark-solr in intellij

### ISSUE THREAD

**Issue by eakarsu** [lucidworks/spark-solr#213]
I have created a small project in Intellij with built.sbt below. I would like to run all spark-solr applications coming with https://github.com/lucidworks/fusion-spark-bootcamp.All those are using spark-solr library.

//built.sbt
name := "SparkScala"
version := "0.1"
libraryDependencies += "org.scala-lang" % "scala-library" % "2.12.6"
libraryDependencies += "com.lucidworks.spark" % "spark-solr" % "3.4.4"

But sbt is not initializing  and throwing error:

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.restlet.jee#org.restlet;2.3.0: not found
[warn]  :: org.restlet.jee#org.restlet.ext.servlet;2.3.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.restlet.jee:org.restlet:2.3.0
[warn]            +- org.apache.solr:solr-core:7.2.1
[warn]            +- com.lucidworks.spark:spark-solr:3.4.4 (C:\InterviewPreps\react\SparkScala\build.sbt#L7-8)
[warn]            +- default:sparkscala_2.12:0.1
[warn]          org.restlet.jee:org.restlet.ext.servlet:2.3.0
[warn]            +- org.apache.solr:solr-core:7.2.1
[warn]            +- com.lucidworks.spark:spark-solr:3.4.4 (C:\InterviewPreps\react\SparkScala\build.sbt#L7-8)
[warn]            +- default:sparkscala_2.12:0.1
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.restlet.jee#org.restlet;2.3.0: not found

[error] unresolved dependency: org.restlet.jee#org.restlet.ext.servlet;2.3.0: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:334)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)

**Comment by kiranchitturi** [comment]
I think you need to add this to the repositories/resolvers section in the sbt file https://github.com/LucidWorks/spark-solr/blob/b6defa4839a40a5101cdcaf2237f73ae0ac32574/pom.xml#L50. That should resolve those two dependencies.

**Comment by kiranchitturi** [comment]
Check #195  too

**Comment by eakarsu** [comment]
Thanks for instant help
I converted sbt to pom.xml and added your repositories and not getting error.
But now, I am getting compile error when I compile (https://github.com/lucidworks/fusion-spark-bootcamp/blob/master/labs/movielens/load_solr.scala)

For example, compiler is not resolving SparkShellSupport in first line  and udf in the second 
val dataDir = com.lucidworks.spark.util.SparkShellSupport.prop("dataDir").get

spark.udf.register("toInt", (str: String) => str.toInt)

Any thing I missed?

Thanks

**Comment by kiranchitturi** [comment]
ah, looks like you are using Fusion. Instead of adding a dependency on spark-solr, you should add the lib folder as deps `${FUSION_HOME}/apps/libs`. `SparkShellSupport` comes from Fusion libs

**Comment by eakarsu** [comment]
That is my fault. I need to create Spark session manually. That issue has gone. But I am getting different problem. Fusion is running in local vagrant machine and try to connect from host machine. I have set up "zkhost" but getting this problem

 var writeToSolrOpts = Map("collection" -> "users", "soft_commit_secs" -> "10", "zkhost" -> "192.168.1.188:9983")
    userDF.write.format("solr").options(writeToSolrOpts).save

Exception in thread "main" com.google.common.util.concurrent.UncheckedExecutionException: org.apache.solr.common.SolrException: Cannot connect to cluster at 192.168.1.188:9983: cluster not found/not ready
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2263)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4004)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4874)
	at com.lucidworks.spark.util.SolrSupport$.getCachedCloudClient(SolrSupport.scala:246)
	at com.lucidworks.spark.util.SolrSupport$.getSolrBaseUrl(SolrSupport.scala:250)
	at com.lucidworks.spark.SolrRelation.insert(SolrRelation.scala:630)
	at solr.DefaultSource.createRelation(DefaultSource.scala:27)

**Comment by kiranchitturi** [comment]
We should move to fusion-spark-bootcamp. I don't think this issue is related to spark-solr anymore
