### ISSUE TITLE
DocValue false and Stored false fields are attempting to be created on index time

### ISSUE THREAD

**Issue by thejerrybao** [lucidworks/spark-solr#224]
https://github.com/lucidworks/spark-solr/blob/43a49fba9e673d8f6e75cec5b59d02ab3a68f0f3/src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala#L345-L347

When attempting to index into fields that are non-stored and non-docvalues, spark attempts to create the fields before indexing them. The fields exist already so they should be skipped over.

In addition...
https://github.com/lucidworks/spark-solr/blob/43a49fba9e673d8f6e75cec5b59d02ab3a68f0f3/src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala#L271

Dynamic fields aren't being filtered out for indexing.

**Comment by kiranchitturi** [comment]
@thejerrybao Finally got time to fix this issue. Can you check out https://github.com/lucidworks/spark-solr/pull/227 ?

```
 fieldDefinitionsFromSchema.filterKeys(k => if (skipDynamicExtensions) !k.startsWith("*_") && !k.endsWith("_*") else true).foreach {
```

The above line skips fields `*_s`, etc.. from the schema. We do filter out dynamic field names here 

https://github.com/lucidworks/spark-solr/blob/43a49fba9e673d8f6e75cec5b59d02ab3a68f0f3/src/main/scala/com/lucidworks/spark/SolrRelation.scala#L657

I have added a test here https://github.com/lucidworks/spark-solr/pull/227/files#diff-56e75c0dfecd9c6ad7c312bfdb924e60R74

Could you please take a look and let me know if I am not missing something here that you think is a bug?

**Comment by thejerrybao** [comment]
@kiranchitturi awesome thanks for the fix! Looks great to me.

In regards to the dynamic field names, in my testing (several weeks ago), I found that they weren't being filtered out. Maybe a test to see if they're filtered out would help?

**Comment by kiranchitturi** [comment]
@thejerrybao Thanks for getting back!

I have added dynamic field names to the test here https://github.com/lucidworks/spark-solr/pull/227/files#diff-56e75c0dfecd9c6ad7c312bfdb924e60R74 

In the test fields `a_s`, `s_a` are being filtered out as they match `*_s` and `s_*` patterns in dynamic names. Was there any particular dynamic field that was not filtered out in your test?

**Comment by kiranchitturi** [comment]
hmm yeah. I was thinking one wouldn't use those as field names in a document while indexing to Solr

**Comment by thejerrybao** [comment]
@kiranchitturi Could I get a 3.5.5 release to use the fix? :)

**Comment by kiranchitturi** [comment]
@thejerrybao 3.5.5 fix has been out http://repo1.maven.org/maven2/com/lucidworks/spark/spark-solr/3.5.5/. I forgot to update the README

**Comment by thejerrybao** [comment]
Ah okay thanks @kiranchitturi; didnt check the maven repo and only looked at the tags here haha.

**Comment by kiranchitturi** [comment]
my bad there. I did the release but forgot to push the tags
