### ISSUE TITLE
can't insert dataframe into solr

### ISSUE THREAD

**Issue by vishnu41** [lucidworks/spark-solr#226]
I'm trying to add data frame into solr in the following way...
`    val writeToSolrOpts = Map(
      "zkhost" -> "localhost:2181",
      "collection" -> "test-solr-spark"
    )
      df.write.format("solr").options(writeToSolrOpts).mode(org.apache.spark.sql.SaveMode.Append).save
`
Only fields are getting added but not data. I am getting the error: task not serializable.

**Comment by kiranchitturi** [comment]
Please share the full error message and stacktrace. See https://jaceklaskowski.gitbooks.io/mastering-apache-spark/spark-tips-and-tricks-sparkexception-task-not-serializable.html
