### ISSUE TITLE
spark-solr 3.0.0-beta with spark 2.1.0 scala 2.10 error 

### ISSUE THREAD

**Issue by dumengnan** [lucidworks/spark-solr#228]
it always exception 
java.lang.InstantiationError: com.typesafe.scalalogging.Logger

**Comment by kiranchitturi** [comment]
Please check your dependency tree on any conflicts in scala-logging

**Comment by dumengnan** [comment]
If I want run spark-solr on spark2.1.0 and scala 2.10,is it ok?
