### ISSUE TITLE
Version compatibility table not updated with Solr 7.5 and Spark 2.4

### ISSUE THREAD

**Issue by adrianocarolino** [lucidworks/spark-solr#238]
Looks like the latest code is already merged with Spark 2.4 and Solr 7.5 but I still see the version compatibility table in the home page not updated with new connector version.

**Comment by kiranchitturi** [comment]
@adrianocarolino http://repo1.maven.org/maven2/com/lucidworks/spark/spark-solr/3.6.0/

I have updated the table now
