### ISSUE TITLE
how about performance of count()?

### ISSUE THREAD

**Issue by bluejoe2008** [lucidworks/spark-solr#24]
solr will quickly returns numFound on resposne to a solr query
but i know Spark SQL will re-filter all RDD rows returned by your buildScan(),
so,
do you have any ideas on improve the count()'s performance?

**Comment by thelabdude** [comment]
Why would you want to go through the DataFrame API just to get count? DataFrame is for doing analytics on the actual rows ... if you just need count, go directly to Solr with a query to SolrRDD

**Comment by thelabdude** [comment]
this is fixed in master
