### ISSUE TITLE
Is this project available in any Public Repositories?

### ISSUE THREAD

**Issue by seanpquig** [LucidWorks/spark-solr#27]
I'd like to add this project via Maven or SBT.  Is it available anywhere publicly?  I don't see it on Maven Central.

**Comment by arinconstrio** [comment]
+1

**Comment by jayantshekhar** [comment]
+1 Looking forward to start using it in my projects.

**Comment by kiranchitturi** [comment]
From now on, all spark-solr releases will be available on maven central.

The latest release 1.1.2 is on central (https://github.com/LucidWorks/spark-solr/releases/tag/1.1.2).

**Comment by seanpquig** [comment]
:+1:
