### ISSUE TITLE
Launching Spark Shell with Shaded jar not working with ADD_JAR on Spark 1.5

### ISSUE THREAD

**Issue by jqnik** [LucidWorks/spark-solr#31]
Hi,
if I try to launch as suggested in the Readme on the current master, spark cannot find the solr datasource:

[vagrant@test550-master spark-solr-1.1.2]$ PROJECT_HOME=`pwd` && ADD_JARS=$PROJECT_HOME/target/spark-solr-1.0-SNAPSHOT-shaded.jar spark-shell
...
scala> val poems = sqlContext.load("solr", Map("zkHost" -> "test550-master:2181/solr", "collection" -> "poems"))
warning: there were 1 deprecation warning(s); re-run with -deprecation for details
java.lang.ClassNotFoundException: Failed to load class for data source: solr.
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.lookupDataSource(ResolvedDataSource.scala:67) 

Invoking spark-shell with the following options fixes this for me:

PROJECT_HOME=`pwd` && spark-shell --jars $PROJECT_HOME/target/spark-solr-1.2.0-SNAPSHOT-shaded.jar --driver-class-path $PROJECT_HOME/target/spark-solr-1.2.0-SNAPSHOT-shaded.jar

scala> val poems = sqlContext.load("solr", Map("zkHost" -> "test550-master:2181/solr", "collection" -> "poems"))
warning: there were 1 deprecation warning(s); re-run with -deprecation for details
2016-01-05 14:56:36,987 [main] INFO  SolrZkClient  - Using default ZkCredentialsProvider
2016-01-05 14:56:37,032 [main] INFO  ConnectionManager  - Waiting for client to connect to ZooKeeper
2016-01-05 14:56:37,054 [zkCallback-2-thread-1] INFO  ConnectionManager  - Watcher shaded.apache.solr.common.cloud.ConnectionManager@7d401432 name:ZooKeeperConnection Watcher:test550-master:2181/solr got event WatchedEvent state:SyncConnected type:None path:null path:null type:None
2016-01-05 14:56:37,055 [main] INFO  ConnectionManager  - Client is connected to ZooKeeper
2016-01-05 14:56:37,055 [main] INFO  SolrZkClient  - Using default ZkACLProvider
2016-01-05 14:56:37,059 [main] INFO  ZkStateReader  - Updating cluster state from ZooKeeper...
2016-01-05 14:56:37,545 [main] WARN  HiveConf  - HiveConf of name hive.enable.spark.execution.engine does not exist
poems: org.apache.spark.sql.DataFrame = [id: string, text: string, _version_: bigint]

scala>

The ADD_JAR option does however work with the 1.1.2 release.

**Comment by kiranchitturi** [comment]
@jqnik Which version of Spark are you using? The `ADD_JARS` option worked fine for me. 

```scala
Kirans-MacBook-Pro:spark-1.5.2-bin-hadoop2.4 kiran$ ADD_JARS=~/Git/spark-solr/target/spark-solr-1.2.0-SNAPSHOT-shaded.jar bin/spark-shell
Using Spark's repl log4j profile: org/apache/spark/log4j-defaults-repl.properties
To adjust logging level use sc.setLogLevel("INFO")
16/01/13 17:26:03 WARN SparkILoop: ADD_JARS environment variable is deprecated, use --jar spark submit argument instead
16/01/13 17:26:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.5.2
      /_/

Using Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_51)
Type in expressions to have them evaluated.
Type :help for more information.
16/01/13 17:26:06 WARN SparkILoop: ADD_JARS environment variable is deprecated, use --jar spark submit argument instead
16/01/13 17:26:07 WARN MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
Spark context available as sc.
16/01/13 17:26:12 WARN ObjectStore: Version information not found in metastore. hive.metastore.schema.verification is not enabled so recording the schema version 1.2.0
16/01/13 17:26:12 WARN ObjectStore: Failed to get database default, returning NoSuchObjectException
16/01/13 17:26:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
SQL context available as sqlContext.

scala> val social = sqlContext.load("solr", Map("zkHost" -> "localhost:9983", "collection" -> "socialdata"))
warning: there were 1 deprecation warning(s); re-run with -deprecation for details
social: org.apache.spark.sql.DataFrame = [_indexed_at_tdt: timestamp, _version_: bigint, accessLevel_i: int, author_s: string, createdAt_tdt: timestamp, currentUserRetweetId_l: bigint, favorited_b: boolean, id: string, id_l: bigint, inReplyToScreenName_s: string, inReplyToStatusId_l: bigint, inReplyToUserId_l: bigint, possiblySensitive_b: boolean, provider_s: string, retweetCount_l: bigint, retweet_b: boolean, retweetedByMe_b: boolean, source_t: array<string>, text_s: string, text_t: array<string>, truncated_b: boolean, type_s: string]

scala> 
```

Anyways, the `ADD_JARS` env variable is deprecated and it is recommended to use `--jar`. I will update the documentation with the `--jar` argument

**Comment by jqnik** [comment]
I used 1.5.0 + Cloudera patches. Yes, makes sense (document --jar). Thus, in my opinion, we can close this.
