### ISSUE TITLE
Is this a dead or orphaned project now?

### ISSUE THREAD

**Issue by theoathinas** [lucidworks/spark-solr#318]
Hello, should this project (or at least, this official repo) be considered abandoned? Has Lucidworks given up on maintaining this connector because they no longer use it themselves? There hasn't been any updates to master in almost a year, and not a lot of responses to the PRs coming in. Some of the recent PRs related to upgrading to Spark 3 and Solr 8.8.x are very interesting (we started using them in production in our own forked repo), and we are wondering if there any plans to incorporate any new features/performance improvements, or if using the spark-solr connector is no longer the recommended way of interacting with solr within Spark?

**Comment by falloutdurham** [comment]
Hi! There should be a release in May, I think, which will be mainly a bug-fix and 8.8.x'd themed one, but hopefully a new major version will also be in the offing bring Spark 3 support in the Summer.
