### ISSUE TITLE
can not use it with solr5.0.0 in cluster mode

### ISSUE THREAD

**Issue by purohitsumit** [LucidWorks/spark-solr#4]
Out of box pom.xml which uses solrj and solr-core 4.10.3 gives 
015-03-28 22:43:46,650 [Executor task launch worker-0] ERROR Executor  - Exception in task 0.0 in stage 6.0 (TID 6)
org.apache.solr.common.SolrException: Could not find collection : <name of collection>

If i compile this with solrJ5.0.0 and solr-core 5.0.0 i get

 2015-03-28 23:04:09,014 [Executor task launch worker-1] ERROR Executor  - Exception in task 1.0 in stage 8.0 (TID 16)
java.lang.Error: Unresolved compilation problem: 
	Type mismatch: cannot convert from CloudSolrServer to SolrServer

	at com.lucidworks.spark.SolrSupport$4.call(SolrSupport.java:162)

**Comment by thelabdude** [comment]
The project only works with Solr 5.x for now ... time to upgrade ;-)
