### ISSUE TITLE
Solr date format problems

### ISSUE THREAD

**Issue by marcino239** [lucidworks/spark-solr#40]
Hi All,

When running a query in spark for a particular date via spark-solr plugin I get solr exception "Invalid Date String".  It looks like spark-solr plugin is converting java.sql.Timestamp to format "yyyy-MM-dd hh:MM:ss" instead of sorl required UTC format:  "yyyy-MM-dd'T'hh:MM:ss'Z'".  I've tracked that the conversion takes place here: SolrRelation.fq( Filter f ) with direct call to String.valueOf( eq.value ) - lines circa 254 in SolrRelation.java.  I'm using branch spark1_5_x.

Let me know if this is a bug or I'm not using it correctly.  My query is:

sqlContext.sql( "select count(*) from some_table where Date_='2015-11-30 00:00:00.0'" ).show()

Thanks,
Marcin

**Comment by kiranchitturi** [comment]
Hi @marcino239. This looks like a bug on the spark-solr code side. 

The date query in your example is not a valid query. You would need to specify date range queries in the SQL query.

A likely example would be:

```
sqlContext.sql( "select count(*) from some_table where Date_='2015-11-30 00:00:00.0 TO 2015-12-30 00:00:00.0'" ).show()
```

I am working currently on master to fix this

**Comment by kiranchitturi** [comment]
btw, your sql query is valid. I was wrong. See https://github.com/lucidworks/spark-solr/commit/bf6855e0c2afffde22c59dc96038eb4793e7e87d#diff-e5af834951f2ca15b6243e6248089a3fR128 for example

**Comment by Cheers0606** [comment]
Hi @kiranchitturi . It works when I search like
```
sqlContext.sql( "select count(*) from some_table where OBJ_TYPE=1 AND OSD_TIME=\"2017-05-25 13:57:00\" limit 1000 )
```
== Analyzed Logical Plan ==
   +- Filter ((OBJ_TYPE#1083L = cast(1 as bigint)) && (OSD_TIME#1076 = cast(2017-05-25T13:57:00Z as timestamp)))
But when it comes to
```
sqlContext.sql( "select count(*) from some_table where OBJ_TYPE=1 AND OSD_TIME=\"2017-05-25 13:57:00 TO 2017-05-26 13:57:00\" limit 1000 )
```
it can not work.
== Analyzed Logical Plan ==
   +- Filter ((OBJ_TYPE#927L = cast(1 as bigint)) && (OSD_TIME#920 = cast(2017-05-25T13:57:00Z TO 2017-05-26T13:57:00Z as timestamp)))

could u tell me how to deal with it.
(the version I use is [spark-sql_2.10-1.6.1.jar])
