### ISSUE TITLE
Not able to index the content of a dataframe(generated from a json file). Method Not Found exception

### ISSUE THREAD

**Issue by Chandanap99** [lucidworks/spark-solr#52]
Hi,

I am trying to index the content of a dataframe (genearte from a simple json file) in solr using the following command: 

`val df = sqlContext.read.json("emp.json");
val solrOpts = Map("zkhost" -> "<ip>:<port>/solr", "collection" -> "sample_test2")
df.write.format("solr").options(solrOpts).mode(org.apache.spark.sql.SaveMode.Append).save()`

I am getting "Method Not Found" exception.
It says 

>  Request to collection mycollection failed due to (405) org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://<ip>:8983/solr/mycollection: Expected mime type application/octet-stream but got text/html.

Can I provide mime type in the **solrOpts **parameter?

Also, when I try to add a document from Apache Solr admin portal, then its getting indexed properly.

The schema.xml file has only three fields:

1. empid (unique)
2. employeename
3. country

Sample json : {"empid":"102","employeename":"Peter","country":"US"}

Thanks

**Comment by kiranchitturi** [comment]
@Chandanap99 Which version of spark-solr are you using or are you building from master ?

What Solr version are you using ?

**Comment by Chandanap99** [comment]
@kiranchitturi I am building 2.1.0-SNAPSHOT of spark-solr
And the solr version is 4.10.

If this is a version compatibility issue, then please let me know which version of spark-solr I should build  to make it compatible with our solr version and to overcome this issue.

Thanks

**Comment by kiranchitturi** [comment]
Can you provide full logs from the script and also from your Solr server ?

**Comment by Chandanap99** [comment]
Script error is attached
[script_error.txt](https://github.com/lucidworks/spark-solr/files/216516/script_error.txt)


sorl server does not show any error. It just has few rows with INFO

Thanks

**Comment by kiranchitturi** [comment]
@Chandanap99 The master branch is tested with Solr version 5.4.1. I can't think of any earlier releases that are compatible with 4.10.

If possible, I would recommend you to use Solr latest 5.4.1. 

Regarding the error you saw `Method not allowed`, I think this is happening because the spark-solr is trying to update your schema via Schema API calls. 

Can you share with us the commands you tried in spark-shell and all the logs from spark-shell REPL ?

**Comment by thelabdude** [comment]
we're not supporting Solr 4.x for this project, upgrade please
