### ISSUE TITLE
join  and  left  join

### ISSUE THREAD

**Issue by ranqiqiang** [lucidworks/spark-solr#57]
SPARK-SQL:  tableA a left join tableB b  where  a.id = 123 and b.id=123
it's  very slowly, the "where"  is not to do in solr.

but I do this SQL:
 tableA a join tableB b  where  a.id = 123 and b.id=123
it's quick

I guess left join  need to update

**Comment by kiranchitturi** [comment]
how slow is the left join query ? How many records do you have in your tableA and tableB collections ?

**Comment by ranqiqiang** [comment]
If I just  use join ,just 3s,   but letf join  use  more than 3mins   ,   tableA and tableB  1000W records,but result just 10 .    

I have other questions,  SQL:"select count(1) from tableA " ,It's  slowly  ,  It's get in Mem?  then count?

**Comment by kiranchitturi** [comment]
Please elaborate your question in a new issue. Closing this as inactive
