### ISSUE TITLE
SQL  IN(ID1,ID2)  not  support

### ISSUE THREAD

**Issue by ranqiqiang** [lucidworks/spark-solr#58]
SPARK-SQL:select \* from TT where id in ('00000525','00000174') limit 1;
not find result,
but do this is oK:
select \* from TT where id in ('00000525'') limit 1;
select \* from TT where id in ('00000174') limit 1;
select \* from TT where id='00000525' or id='00000174' limit 1;

**Comment by kiranchitturi** [comment]
Both expressions are working fine for me. I have tried the below examples:

```
scala> sqlContext.sql("select * from trips where tip_amount='5.0' or tip_amount='15.0'").count()
res16: Long = 3
```

```
scala> sqlContext.sql("select * from trips where tip_amount in ('5.0', '15.0')").count()
res15: Long = 3
```

I would recommend the usage of multiple 'or' expressions instead of the 'in' expression. When multiple 'or' expressions are used, the filtering happens in Solr rather than in Solr

```
scala> sqlContext.sql("select * from trips where tip_amount in ('5.0', '15.0')").explain()
16/05/05 00:30:08 INFO ParseDriver: Parsing command: select * from trips where tip_amount in ('5.0', '15.0')
16/05/05 00:30:08 INFO ParseDriver: Parse Completed
16/05/05 00:30:08 INFO SolrRelation: Constructed SolrQuery: q=*:*&rows=1000&collection=techproducts&distrib=false&start=0&sort=id+asc
== Physical Plan ==
Filter cast(tip_amount#5 as string) IN (5.0,15.0)
+- Scan com.lucidworks.spark.SolrRelation@17f5eaad[improvement_surcharge#0,_indexed_at_tdt#1,vendor_id#2L,trip_distance#3,tolls_amount#4,tip_amount#5,id#6,pickup#7,payment_type#8L,fare_amount#9,passenger_count#10L,dropoff#11,store_and_fwd_flag#12,extra#13,dropoff_datetime#14,_version_#15L,rate_code_id#16L,total_amount#17,pickup_datetime#18,mta_tax#19]
```

```
scala> sqlContext.sql("select * from trips where tip_amount='5.0' or tip_amount='15.0' limit 10").explain()
16/05/05 00:33:03 INFO ParseDriver: Parsing command: select * from trips where tip_amount='5.0' or tip_amount='15.0' limit 10
16/05/05 00:33:03 INFO ParseDriver: Parse Completed
16/05/05 00:33:03 INFO SolrRelation: Constructed SolrQuery: q=*:*&rows=1000&collection=techproducts&fq=(tip_amount:5.0+OR+tip_amount:15.0)&distrib=false&start=0&sort=id+asc
== Physical Plan ==
Limit 10
+- Filter ((tip_amount#5 = 5.0) || (tip_amount#5 = 15.0))
   +- Scan com.lucidworks.spark.SolrRelation@17f5eaad[improvement_surcharge#0,_indexed_at_tdt#1,vendor_id#2L,trip_distance#3,tolls_amount#4,tip_amount#5,id#6,pickup#7,payment_type#8L,fare_amount#9,passenger_count#10L,dropoff#11,store_and_fwd_flag#12,extra#13,dropoff_datetime#14,_version_#15L,rate_code_id#16L,total_amount#17,pickup_datetime#18,mta_tax#19] PushedFilters: [Or(EqualTo(tip_amount,5.0),EqualTo(tip_amount,15.0))]
```

As shown, the filters are pushed and added to solr query only when multiple 'or' expressions are used. Hence this is more efficient

**Comment by ranqiqiang** [comment]
oh~no.why?..my spark  version is  1.6.0,I use spark-sql  or  beeline:jdbc
`spark-sql> select count(1) from waitInstance where entity_id ='00000525' or entity_id='00000174';
385`

`spark-sql> select count(1) from waitInstance where entity_id in ('00000525','00000174');
0`

**Comment by ranqiqiang** [comment]
my sql : select * from orderdetail where entity_id in ('99000908','99180274')  limit 10
and the solr explan is : 
`SolrRelation: Constructed SolrQuery: q=*:*&rows=1000&fl=order_id,is_hide,open_time,end_time,entity_id,status,curr_date,is_valid&collection=search4SingleOrder&fq=entity_id:(99000908+99180274)`

is OK?

**Comment by kiranchitturi** [comment]
Lot of bug fixes have been since this question. Please try with the latest version

If you have the same issue, please elaborate your question in a new issue. Closing this as inactive
