### ISSUE TITLE
jar  in spark-1.6.0

### ISSUE THREAD

**Issue by ranqiqiang** [lucidworks/spark-solr#60]
hello,
     my spark version is 1.6.0
     and add the jar to here:export $SPARK_CLASSPATH:$SPARK_HOME/lib/solr.xxx2.0.jar
     then  I start start-thriftserver.sh  ....
     so,I can  search from solr_table   by   spark-sql  or  beeline.
    but  I use spark-shell,  will  not find a method,the  method in scala-reflect 2.10.5,but your jar used  is 2.10.4.
    
    then I start with "start-thriftserver.sh --jars solr_xx.jar",I can use spark-shell  and beeline,but  spark-sql  can't search from solr_table
   so,should to change it.

thanks

 <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-reflect</artifactId>
            <version>2.10.5</version>
        </dependency>

**Comment by kiranchitturi** [comment]
Thanks for reporting the issue. Will fix it in the next bug release

**Comment by ranqiqiang** [comment]
I'm sorry, It's not a bug, just not to do  with "export $SPARK_CLASSPATH:$SPARK_HOME/lib/solr.xxx2.0.jar"  ,and  if you  use like this " xx.sh  --jars  solr.jar  "  It's  OK!

It's just  not to add this jar  when you start-all  spark
