### ISSUE TITLE
Reading back arrays in a DataFrame no longer work in 2.0.0

### ISSUE THREAD

**Issue by davidtambjss** [lucidworks/spark-solr#62]
Hello,

I was using spark-solr 1.1.2 in java fairly happily up until now.  Then I saw 2.0.0 is out and therefore I tried it out and it broke a lot of our unit tests.
There are 2 issues:

* For int and float, they dont seem to work anymore, when I write to Solr as int and float they are read back as long and double.  Is there a way to read back int and float?  This is a minor and I can probably live with.
* It seems that when I want to read back an array (of any types) as a column in a DataFrame in Spark from Solr, I can only read back the first element with the 2.0.0 library, and it is no longer an array (but just as the underlying type of the array).

e.g. If I have in Solr:
someArray : ["foo", "bar"] 

It used to be able to create:
|-- someArray : array(string) (nullable = true)
as a column in a dataframe in spark when read back, but now I get:
|-- someArray : string (nullable = true)
and the value is just:
"foo"

Is this a bug or there are some parameters I am missing?

**Comment by kiranchitturi** [comment]
> For int and float, they dont seem to work anymore, when I write to Solr as int and float they are read back as long and double. Is there a way to read back int and float? This is a minor and I can probably live with.

Correct. We convert everything to long and double right now. We had to do this because the Streaming expressions in Solr already convert int and float to long and double. Currently, there is no way to read back int/float

> It seems that when I want to read back an array (of any types) as a column in a DataFrame in Spark from Solr, I can only read back the first element with the 2.0.0 library, and it is no longer an array (but just as the underlying type of the array).

https://github.com/lucidworks/spark-solr#flatten_multivalued

btw, the latest released version is 2.0.1

**Comment by kiranchitturi** [comment]
> I was using spark-solr 1.1.2 in java fairly happily up until now. Then I saw 2.0.0 is out and therefore I tried it out and it broke a lot of our unit tests.

RDD compatibility broke between 1.1.2 and 2.x too. If you are using RDDs, you should take a look at https://github.com/lucidworks/spark-solr#via-rdd-java

**Comment by davidtambjss** [comment]
@kiranchitturi Thank you.  After changing the options all the tests passed.  This also helps when data is written to solr in schemaless / managed schema mode where one probably want to have value automatically flattened.
I am not using rdd but thanks for the heads up on SolrRdd

**Comment by kiranchitturi** [comment]
👍
