### ISSUE TITLE
too many "OR"  not support!

### ISSUE THREAD

**Issue by ranqiqiang** [lucidworks/spark-solr#63]
hello
      I run a SQL like this:"select \* from table where id='123' or id ='345' or id = '456' "
throw exception:
`Error: java.lang.IllegalArgumentException: Filters of type 'Or(EqualTo(order_id,99001331547aa1ad01547aa1e89b0042),EqualTo(order_id,99001331547b710f01547b71bc060066)) (org.apache.spark.sql.sources.Or)' not supported! (state=,code=0)`

but  just  two "OR"  is OK! can you help me?

**Comment by kiranchitturi** [comment]
Is there a full stack trace to this ? I think the error is coming from Spark itself

**Comment by kiranchitturi** [comment]
Lot of bug fixes have been since this question. Please try with the latest version

If you have the same issue, please elaborate your question in a new issue. Closing this as inactive
