### ISSUE TITLE
{!terms f=order_id}123,123  not support!

### ISSUE THREAD

**Issue by ranqiqiang** [lucidworks/spark-solr#64]
dear :
       I use query like this ：
    `JavaRDD<SolrDocument> resultsRDD = solrRDD.query("{!terms f=order_id}0000133152f850840152f872c57d00bc");`

```
 but the resultsRDD.count()=0;
```

   if I  use  `JavaRDD<SolrDocument> resultsRDD = solrRDD.query("order_id:0000133152f850840152f872c57d00bc");`

   resultsRDD.count()  > 0 

The util not do that ?

**Comment by kiranchitturi** [comment]
Lot of bug fixes have been since this question. Please try with the latest version

If you have the same issue, please elaborate your question in a new issue. Closing this as inactive
