### ISSUE TITLE
unresolved dependency: com.lucidworks.solr#spark-solr;2.0.1: not found

### ISSUE THREAD

**Issue by lefromage** [lucidworks/spark-solr#66]
$SPARK_HOME/bin/spark-shell --packages "com.lucidworks.solr:spark-solr:2.0.1"

cannot get the correct jar
https://repo1.maven.org/maven2/com/lucidworks/spark/spark-solr/2.0.1/spark-solr-2.0.1-shaded.jar

instead tries to get :

	==== central: tried

	  https://repo1.maven.org/maven2/com/lucidworks/solr/spark-solr/2.0.1/spark-solr-2.0.1.pom

	  -- artifact com.lucidworks.solr#spark-solr;2.0.1!spark-solr.jar:

	  https://repo1.maven.org/maven2/com/lucidworks/solr/spark-solr/2.0.1/spark-solr-2.0.1.jar

	==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/com/lucidworks/solr/spark-solr/2.0.1/spark-solr-2.0.1.pom

	  -- artifact com.lucidworks.solr#spark-solr;2.0.1!spark-solr.jar:

	  http://dl.bintray.com/spark-packages/maven/com/lucidworks/solr/spark-solr/2.0.1/spark-solr-2.0.1.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: com.lucidworks.solr#spark-solr;2.0.1: not found

		::::::::::::::::::::::::::::::::::::::::::::::

:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.lucidworks.solr#spark-solr;2.0.1: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1011)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:286)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by epugh** [comment]
I believe you have the wrong dependency path.   I checked and it's there at https://repo1.maven.org/maven2/com/lucidworks/spark/spark-solr/2.0.1/.

try: `com.lucidworks.spark#spark-solr;2.0.1`

**Comment by kiranchitturi** [comment]
@lefromage I got the package wrong in the documentation. It should be `com.lucidworks.spark` instead of `com.lucidworks.solr`.  fixing it in the README

This should work

```
./bin/spark-shell --packages "com.lucidworks.spark:spark-solr:2.0.1"
```
