### ISSUE TITLE
NoSuchMethodError: scala.reflect.NameTransformer$.LOCAL_SUFFIX_STRING()Ljava/lang/String;

### ISSUE THREAD

**Issue by scarton** [lucidworks/spark-solr#71]
Using Version 2.0.1, version 1.6.1 of Spark, Java Version 1.8 and Solr 5.3.1, the following Java code fails immediately with tthe exception above. The query is a SolrQuery object. I can post more if needed, but is this a spark version mismatch of some kind?

JavaPairRDD<String, ArrayRIV> drRdd = SolrJavaRDD.get(props.zkHosts(), props.collection(), jsc.sc())
			.queryShards(query)

**Comment by kiranchitturi** [comment]
@scarton 

You might have different versions of Scala libraries in your classpath. Check your other dependencies if they are bringing in other versions of Scala.

**Comment by scarton** [comment]
Thanks for the tip. I did find and eliminate a conflict in my dependencies - I was using 2.11 and it seems you are using 2.10? I have it working now with that.

**Comment by kiranchitturi** [comment]
yeah, the current master is on 2.10. We are moving to 2.11 along with the spark 2.0.0 upgrade
