### ISSUE TITLE
many rows! exception

### ISSUE THREAD

**Issue by ranqiqiang** [lucidworks/spark-solr#74]
I use query `{!terms f=id}id1,id2...` 
Maybe have  2000-5000 ids，then run the exception

`Most likely this means your query's sort criteria is not generating stable results for computing deep-paging cursors, has the index changed? If so, try using a filter criteria the bounds the results to non-changing data.`

I don't how to solve it!
can you help me?

Email:greemqqran@163.com

**Comment by thelabdude** [comment]
Try enabling splits or using the /export handler instead.

**Comment by kiranchitturi** [comment]
Lot of bug fixes have been since this question. Please try with the latest version

If you have the same issue, please elaborate your question in a new issue. Closing this as inactive
