### ISSUE TITLE
Filtering on an indexed text field doesnt honour quotations in phrase queries

### ISSUE THREAD

**Issue by williedoran** [lucidworks/spark-solr#78]
When the filter query is built for a text field it strips all the quotations from the string. So im my solr query i would run something like this, 
q=:*:&fq=body:"William Doran" and this will search for a phrase query and for example i get back 200 documents

however, when i load up my solr index as a DF or RDD, and issue a similar query 
df.where("body = \"William Doran\"").select("id").take(1) this gets translated into
q=:*:&fq=body:William Doran without the quotation marks and causes a term query with the two terms which attempts to return 10million results......BOOM!
i have tried the same with spark SQL but the same behaviour occurs. any ideas on where to look in the code to figure out where the fq filters are being parsed and converted. 

Id also be keen to know why you can only provide a standard query param at config time instead of only using (fq), It seems as tho this would be useful to be able to provide a q param when issuing a select or filter command in a dataset/rdd

**Comment by kiranchitturi** [comment]
@williedoran you can provide any arbitrary param at query time. See https://github.com/LucidWorks/spark-solr#solrparams

Regarding `fq`, this code (https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala#L122) is called from `SolrRelation` class (https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/com/lucidworks/spark/SolrRelation.scala#L247)

In this case, I wonder if Scala passes down or strips down the quotes when passing down the filters. I will take a look later

**Comment by williedoran** [comment]
thanks for the reply @kiranchitturi. yes i saw the solr.params option in the wiki, but my understanding is it only applies for when you load the Dataframe first time, and this query is used on every action within the Dataframe. I guess my use-case is different where i want to do a different query each time and not just (q=*:*) and also filter down by timestamps. 

Essentially my use case is to join a big DB table of peoples names and search for those names in an indexed field in Solr, based on the persons name and a date range. Being able to issue both a  "q=body:"William Doran"&fq=[NOW TO THEN] would be useful in my use case but i can see that this doesnt fit nicely the way the "where clauses"/df.filter() operations are mapped.

If i can get to the bottom of why the fq param is stripping off the quotations, then i guess i can use a fq for both my main query and the date range. I wont get any of solr scoring ranking but i can live with that i think.

**Comment by kiranchitturi** [comment]
Lot of bug fixes have been pushed since this question. Please try with the latest version

If you have the same issue, please elaborate your question in a new issue. Closing this as inactive
