### ISSUE TITLE
collection not set in solrRDD

### ISSUE THREAD

**Issue by shanich** [LucidWorks/spark-solr#8]
i execute the code that get the solr into RDD
JavaRDD<SolrDocument> solrJavaRDD = solrRDD.query(jsc, solrQuery, useDeepPagingCursor);

i got an exception:
solrrdd org.apache.solr.client.solrj.SolrServerException: No collection param specified on request and no default collection has been set.

i fount that the solrRDD inside of function get set the collection by 
params.set("collection", collection);

instead of 
cloudSolrServer.setDefaultCollection(collection);

i changed it in mycode and it fixed the issue.

**Comment by thelabdude** [comment]
I think this has been fixed? Please verify
