### ISSUE TITLE
Cannot set the number of rows to None

### ISSUE THREAD

**Issue by younes-abouelnagah** [lucidworks/spark-solr#85]
The SolrRDD accepts a number of rows which is an Option, but setting it to None will cause an Exception from [this line](https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala#L174) because it is calling `None.get`. That line is actually meaningless as it is right now, and I think the condition should be modified. I think it makes more sense to check if `rows.isDefined` and set the number of rows in the query accordingly.

**Comment by younes-abouelnagah** [comment]
I verified that the rows parameter doesn't have an effect on the number of rows in the RDD or the DataFrame, but rather is an internal configuration for how SolrRDD communicates with Solr. Using the default rows of 1000, I could load much more data from Solr.

**Comment by kiranchitturi** [comment]
yeah. The rows param should only be used to configure the number of rows to retrieve in a single HTTP call to the shard. By default, all the data is fetched by using deep paging with cursorMarks or streaming.

**Comment by kiranchitturi** [comment]
If your documents are tiny and if the cluster has more memory, use the default of `10000`

**Comment by younes-abouelnagah** [comment]
Thanks for that reconfirmation. There is still a bug when rows is set to None. It should be a rows.getOrElse(DEFAULT) then None will not cause an exception. Or make it a straight int with a default value. Thanks!

**Comment by kiranchitturi** [comment]
Thanks for reporting this. I pushed a fix for it. It will be in the next release version
