### ISSUE TITLE
Spark 2.0 support

### ISSUE THREAD

**Issue by francoisfernando** [lucidworks/spark-solr#86]
I see that there is already a branch to support Spark 2.0. Any idea when you guys are planning to release it?

**Comment by kiranchitturi** [comment]
@francoisfernando 

There is a bug (https://issues.apache.org/jira/browse/SPARK-16698) in Spark 2.0 that is holding us from merging the upgrade branch to master. As soon as 2.0.1/2.1 is released, we will do a new release.

**Comment by francoisfernando** [comment]
@kiranchitturi Thanks for the heads up.

**Comment by kiranchitturi** [comment]
I have published a new release (3.0.0-alpha.1) that supports Spark 2.0.1 and Solr 6.2.1 http://search.maven.org/#artifactdetails%7Ccom.lucidworks.spark%7Cspark-solr%7C3.0.0-alpha.1%7Cjar

We will do a major release soon

**Comment by kiranchitturi** [comment]
Please check https://github.com/lucidworks/spark-solr#version-compatibility
