### ISSUE TITLE
spark-solr version 1.1.2

### ISSUE THREAD

**Issue by chetasjoshi** [lucidworks/spark-solr#93]
Hello,

I am using spark-solr jar but an older version 1.1.2. I am using the following options for Querying Solr.

options = Map(
      "collection" -> collection,
      "zkhost" -> zkHost,
      "request_handler" -> "/export",
      "flatten_multivalued" -> "false"
)
sqlConT.read.format("solr").options(options).load()

I am just wondering what API is being used underneath? Is it the streaming API (with /export handler) or something else?

Thanks.

**Comment by kiranchitturi** [comment]
@chetasjoshi yes, Solr's export handler is used underneath https://cwiki.apache.org/confluence/display/solr/Exporting+Result+Sets

**Comment by kiranchitturi** [comment]
See https://github.com/lucidworks/spark-solr/blob/master/src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala#L89 for more details
